import type{WorkflowDefinitionInput}from"./types";
export type WorkflowTemplate={key:string;name:string;description:string;definition:WorkflowDefinitionInput};
export const workflowTemplates:WorkflowTemplate[]=[
 {key:"deployment_failure",name:"Deployment failure review",description:"Create evidence, request owner approval and queue the existing GitHub sync job.",definition:{name:"Deployment failure review",description:"Deterministic deployment recovery with human approval.",triggerType:"notification.created",steps:[{name:"Assign investigation",type:"task",assignedRole:"manager",configuration:{dueHours:4}},{name:"Owner approval",type:"approval",assignedRole:"owner",configuration:{dueHours:8}},{name:"Queue provider sync",type:"integration_action",configuration:{action:"sync",provider:"github"}},{name:"Complete",type:"complete",configuration:{}}]}},
 {key:"integration_reconnect",name:"Integration reconnect",description:"Confirm reconnection and queue a health refresh.",definition:{name:"Integration reconnect",description:"Validate a stored reconnection.",triggerType:"integration.reconnected",steps:[{name:"Confirm account",type:"manual_confirmation",assignedRole:"admin",configuration:{}},{name:"Queue health refresh",type:"background_job",configuration:{jobKey:"integration.health"}},{name:"Complete",type:"complete",configuration:{}}]}},
 {key:"csv_import_review",name:"CSV import review",description:"Review rejected import rows.",definition:{name:"CSV import review",description:"Human review for persisted CSV results.",triggerType:"csv_import.failed",steps:[{name:"Review import evidence",type:"task",assignedRole:"manager",configuration:{dueHours:24}},{name:"Approve remediation",type:"approval",assignedRole:"admin",configuration:{dueHours:24}},{name:"Complete",type:"complete",configuration:{}}]}},
 {key:"correlation_review",name:"Correlation review",description:"Review deterministic correlation evidence.",definition:{name:"Correlation review",description:"Human review without causation claims.",triggerType:"correlation.created",steps:[{name:"Inspect evidence",type:"task",assignedRole:"manager",configuration:{dueHours:24}},{name:"Manual confirmation",type:"manual_confirmation",assignedRole:"manager",configuration:{}},{name:"Complete",type:"complete",configuration:{}}]}},
 {key:"background_job_recovery",name:"Background job recovery",description:"Approve and queue a failed job retry.",definition:{name:"Background job recovery",description:"Controlled recovery for a durable job failure.",triggerType:"background_job.failed",steps:[{name:"Review safe error",type:"task",assignedRole:"manager",configuration:{dueHours:2}},{name:"Approve retry",type:"approval",assignedRole:"admin",configuration:{dueHours:4}},{name:"Queue retry",type:"background_job",configuration:{jobKeyFromTrigger:"jobKey"}},{name:"Complete",type:"complete",configuration:{}}]}},
];
export const getWorkflowTemplate=(key:string)=>workflowTemplates.find(x=>x.key===key);
