import "server-only";
import type {ConnectorCredentialUpdate} from "../connector";
import {gscOAuthEnv,GSC_LIMITS} from "./config";
import type {Inspection,SearchRow,Sitemap} from "./types";
export class SearchConsoleError extends Error{constructor(public kind:"unauthorized"|"forbidden"|"rate_limit"|"timeout"|"provider",message:string){super(message)}}
export class SearchConsoleClient{
  private access:string;private expiry?:string;private updated?:ConnectorCredentialUpdate;private requests=0;
  constructor(private credentials:{accessToken:string;refreshToken?:string;expiresAt?:string},private request:typeof fetch=fetch){this.access=credentials.accessToken;this.expiry=credentials.expiresAt}
  credentialUpdate(){return this.updated}
  private async token(){if(!this.expiry||Date.parse(this.expiry)>Date.now()+60_000)return this.access;if(!this.credentials.refreshToken)throw new SearchConsoleError("unauthorized","Google authorization expired. Reconnect Search Console.");const env=gscOAuthEnv(),response=await this.request("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:env.clientId,client_secret:env.clientSecret,grant_type:"refresh_token",refresh_token:this.credentials.refreshToken}),signal:AbortSignal.timeout(15_000)}),body=await response.json()as{access_token?:string;expires_in?:number};if(!response.ok||!body.access_token)throw new SearchConsoleError("unauthorized","Google authorization could not be refreshed.");this.access=body.access_token;this.expiry=new Date(Date.now()+(body.expires_in??3600)*1000).toISOString();this.updated={accessToken:this.access,refreshToken:this.credentials.refreshToken,expiresAt:this.expiry};return this.access}
  private async call<T>(url:string,init?:RequestInit){if(++this.requests>GSC_LIMITS.requests)throw new SearchConsoleError("rate_limit","Search Console sync stopped at its request safety limit.");let response:Response;try{response=await this.request(url,{...init,headers:{Authorization:`Bearer ${await this.token()}`,...init?.headers},signal:AbortSignal.timeout(15_000)})}catch{throw new SearchConsoleError("timeout","Google Search Console timed out.");}if(!response.ok)throw new SearchConsoleError(response.status===401?"unauthorized":response.status===403?"forbidden":response.status===429?"rate_limit":"provider",response.status===403?"Search Console property permission was denied.":"Google Search Console request failed.");return response.json()as Promise<T>}
  async properties(){const data=await this.call<{siteEntry?:{siteUrl:string;permissionLevel:string}[]}>("https://www.googleapis.com/webmasters/v3/sites");return(data.siteEntry??[]).slice(0,100).map(p=>({...p,type:p.siteUrl.startsWith("sc-domain:")?"domain"as const:"url_prefix"as const}))}
  async search(siteUrl:string,startDate:string,endDate:string){const data=await this.call<{rows?:SearchRow[]}>(`https://www.googleapis.com/webmasters/v3/sites/${encodeURIComponent(siteUrl)}/searchAnalytics/query`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({startDate,endDate,dimensions:["page","query","country","device"],rowLimit:GSC_LIMITS.rowsPerProperty,dataState:"final"})});return data.rows??[]}
  async sitemaps(siteUrl:string){const data=await this.call<{sitemap?:Sitemap[]}>(`https://www.googleapis.com/webmasters/v3/sites/${encodeURIComponent(siteUrl)}/sitemaps`);return(data.sitemap??[]).slice(0,100)}
  async inspect(siteUrl:string,inspectionUrl:string){const data=await this.call<{inspectionResult?:{indexStatusResult?:Omit<Inspection,"inspectionUrl">}}>("https://searchconsole.googleapis.com/v1/urlInspection/index:inspect",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({inspectionUrl,siteUrl})});return{inspectionUrl,...data.inspectionResult?.indexStatusResult}}
  async revoke(){try{await this.request(`https://oauth2.googleapis.com/revoke?token=${encodeURIComponent(await this.token())}`,{method:"POST"})}catch{}}
}
