import {createHash} from "node:crypto";
import type {NormalisedEventInput} from "@/types/events";
import type {TranslationContext} from "../connector";
import type {PropertySnapshot,SearchRow} from "./types";
const clean=(value:string,n=300)=>value.replace(/[\u0000-\u001f\u007f<>]/g," ").replace(/\s+/g," ").trim().slice(0,n);
const key=(row:SearchRow)=>row.keys?.slice(0,4).join("|")??"";
const safePath=(url:string)=>{try{const parsed=new URL(url);return clean(`${parsed.pathname}${parsed.search}`,300)}catch{return clean(url,300)}};
const hash=(value:string)=>createHash("sha256").update(value).digest("hex").slice(0,20);
export function translateSearchConsole(snapshot:PropertySnapshot,ctx:TranslationContext,settings:{thresholdPercent?:number;minimumClicks?:number}):NormalisedEventInput[]{
  const events:NormalisedEventInput[]=[],threshold=settings.thresholdPercent??25,minimum=settings.minimumClicks??10,occurredAt=`${snapshot.current.endDate}T23:59:59.000Z`,property=snapshot.property.siteUrl;
  const add=(type:string,title:string,severity:NormalisedEventInput["severity"],dimension:string,metadata:Record<string,unknown>)=>events.push({organisationId:ctx.organisationId,integrationId:ctx.integrationId,source:"google_search_console",category:"marketing",eventType:type,title:clean(title),severity,occurredAt,externalId:`gsc:${ctx.integrationId}:${hash(property)}:${type}:${snapshot.current.startDate}:${snapshot.current.endDate}:${hash(dimension)}`,metadata:{propertyUrl:property,propertyType:snapshot.property.type,currentStart:snapshot.current.startDate,currentEnd:snapshot.current.endDate,...metadata},rawPayload:{}});
  const current=new Map(snapshot.current.rows.map(row=>[key(row),row])),previous=new Map(snapshot.previous.rows.map(row=>[key(row),row]));
  type Totals={clicks:number;impressions:number;weightedPosition:number};
  const totals=(rows:SearchRow[]):Totals=>rows.reduce<Totals>((sum,row)=>({clicks:sum.clicks+(row.clicks??0),impressions:sum.impressions+(row.impressions??0),weightedPosition:sum.weightedPosition+(row.position??0)*(row.impressions??0)}),{clicks:0,impressions:0,weightedPosition:0});
  const a=totals(snapshot.current.rows),b=totals(snapshot.previous.rows),change=b.clicks?((a.clicks-b.clicks)/b.clicks)*100:null;
  add("google_search_console.performance_summary",`Search performance: ${a.clicks.toLocaleString()} clicks`,"info","summary",{clicks:a.clicks,impressions:a.impressions,ctr:a.impressions?Number((a.clicks/a.impressions).toFixed(4)):0,averagePosition:a.impressions?Number((a.weightedPosition/a.impressions).toFixed(2)):null,rowsAnalysed:snapshot.current.rows.length});
  if(b.clicks>=minimum&&change!==null&&Math.abs(change)>=threshold)add(change>0?"google_search_console.clicks_increased":"google_search_console.clicks_decreased",`Search clicks ${change>0?"increased":"decreased"} ${Math.abs(Math.round(change))}%`,change>0?"good":"warning","total",{currentClicks:a.clicks,previousClicks:b.clicks,percentageChange:Math.round(change*100)/100,currentImpressions:a.impressions,previousImpressions:b.impressions});
  const posA=a.impressions?a.weightedPosition/a.impressions:0,posB=b.impressions?b.weightedPosition/b.impressions:0;if(posA&&posB&&Math.abs(posA-posB)>=2)add(posA<posB?"google_search_console.position_improved":"google_search_console.position_declined",`Average ranking ${posA<posB?"improved":"declined"}`,posA<posB?"good":"warning","position",{currentPosition:Number(posA.toFixed(2)),previousPosition:Number(posB.toFixed(2))});
  for(const [dimension,row] of current){const old=previous.get(dimension),page=row.keys?.[0]??"",query=clean(row.keys?.[1]??"",120);if(!old&&(row.clicks??0)>=minimum){add("google_search_console.new_query_detected",`New search query detected: “${query}”`,"info",dimension,{pagePath:safePath(page),query,clicks:row.clicks??0,impressions:row.impressions??0});continue}if(!old)continue;const oldClicks=old.clicks??0,newClicks=row.clicks??0,pct=oldClicks?((newClicks-oldClicks)/oldClicks)*100:null;if(oldClicks>=minimum&&pct!==null&&Math.abs(pct)>=threshold)add(pct>0?"google_search_console.page_started_ranking":"google_search_console.page_dropped",`${safePath(page)} search clicks ${pct>0?"increased":"dropped"}`,pct>0?"good":"warning",dimension,{pagePath:safePath(page),query,currentClicks:newClicks,previousClicks:oldClicks,percentageChange:Number(pct.toFixed(2)),currentPosition:row.position??null,previousPosition:old.position??null})}
  for(const sitemap of snapshot.sitemaps){const status=(sitemap.errors??0)>0?"failed":(sitemap.warnings??0)>0?"warnings":sitemap.isPending?"submitted":"processed";add(`google_search_console.sitemap_${status}`,`Sitemap ${status}: ${safePath(sitemap.path)}`,status==="failed"?"critical":status==="warnings"?"warning":"info",sitemap.path,{sitemapPath:safePath(sitemap.path),errors:sitemap.errors??0,warnings:sitemap.warnings??0,pending:Boolean(sitemap.isPending)})}
  for(const inspection of snapshot.inspections){const verdict=inspection.verdict??"VERDICT_UNSPECIFIED",coverage=inspection.coverageState??"Unknown";if(verdict==="PASS")add("google_search_console.page_indexed",`Page indexed: ${safePath(inspection.inspectionUrl)}`,"good",inspection.inspectionUrl,{pagePath:safePath(inspection.inspectionUrl),verdict,coverageState:coverage,lastCrawlTime:inspection.lastCrawlTime??null});else add("google_search_console.page_not_indexed",`Page not indexed: ${safePath(inspection.inspectionUrl)}`,inspection.pageFetchState?.includes("SERVER_ERROR")?"critical":"warning",inspection.inspectionUrl,{pagePath:safePath(inspection.inspectionUrl),verdict,coverageState:clean(coverage),pageFetchState:inspection.pageFetchState??null})}
  return events.slice(0,500);
}
