import Link from"next/link";import{getActiveOrganisation}from"@/lib/organisations/active";
const number=(v:unknown)=>v===null||v===undefined?null:Number(v);
const sumMicros=(rows:Record<string,unknown>[])=>rows.reduce((total,row)=>total+BigInt(String((row.metrics as Record<string,unknown>)?.spendMicros??"0")),BigInt(0));
export default async function MetaAdsDashboard({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
  const ctx=await getActiveOrganisation();if(!ctx)return null;const params=await searchParams,days=Math.min(90,Math.max(1,Number(params.days)||7)),now=new Date(),start=new Date(now);start.setUTCDate(start.getUTCDate()-days);
  const{data}=await ctx.supabase.from("events").select("event_type,title,occurred_at,metadata").eq("organisation_id",ctx.organisation.id).eq("source","meta_ads").gte("occurred_at",start.toISOString()).order("occurred_at",{ascending:false}).limit(5000);
  const rows=(data??[]).filter(e=>e.event_type==="meta_ads.performance.daily_recorded").map(e=>e.metadata as Record<string,unknown>),accountRows=rows.filter(r=>r.sourceEntityType==="account"),campaignRows=rows.filter(r=>r.sourceEntityType==="campaign"),currencies=[...new Set(accountRows.map(r=>String(r.currency)))],currency=typeof params.currency==="string"?params.currency:currencies[0],filtered=accountRows.filter(r=>!currency||r.currency===currency),spendMicros=sumMicros(filtered),sum=(field:string)=>filtered.reduce((n,r)=>n+(number((r.metrics as Record<string,unknown>)?.[field])??0),0),reported=(field:string)=>filtered.some(r=>(r.metrics as Record<string,unknown>)?.[field]!==null),campaigns=[...new Map(campaignRows.filter(r=>!currency||r.currency===currency).map(r=>[String(r.sourceEntityId),r])).values()];
  const cards=[["Spend",currency?`${currency} ${(Number(spendMicros)/1e6).toFixed(2)}`:"Not reported"],["Impressions",reported("impressions")?sum("impressions").toLocaleString():"Not reported"],["Reach",reported("reach")?sum("reach").toLocaleString():"Not reported"],["Clicks",reported("clicks")?sum("clicks").toLocaleString():"Not reported"],["Link clicks",reported("linkClicks")?sum("linkClicks").toLocaleString():"Not reported"],["Meta-attributed leads",reported("attributedLeads")?sum("attributedLeads").toLocaleString():"Not reported"],["Meta-attributed purchases",reported("attributedPurchases")?sum("attributedPurchases").toLocaleString():"Not reported"]];
  return <section className="space-y-6"><div className="flex justify-between"><div><h2 className="text-2xl font-bold">Meta Ads reporting</h2><p className="text-zinc-600">Meta unified attribution: 7-day click, 1-day view. This does not prove incremental impact.</p></div><Link className="button button-secondary" href="/app/integrations/meta-ads/settings">Settings</Link></div><form className="card flex gap-3"><select className="input" name="days" defaultValue={days}>{[7,28,90].map(d=><option value={d} key={d}>{d} days</option>)}</select><select className="input" name="currency" defaultValue={currency}>{currencies.map(c=><option key={c}>{c}</option>)}</select><button className="button">Apply</button></form>
  {!rows.length?<div className="card">No Meta Ads reporting data yet. Select accounts and run a sync.</div>:<><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value])=><article className="card" key={label}><p className="text-sm text-zinc-500">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p></article>)}</div><div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-3">Campaign</th><th>Spend</th><th>Impressions</th><th>Reach</th><th>Clicks</th><th>CTR</th><th>Purchases</th><th>ROAS</th></tr></thead><tbody>{campaigns.map(r=>{const m=r.metrics as Record<string,unknown>;return <tr className="border-b" key={String(r.sourceEntityId)}><td className="p-3">{String(r.sourceEntityName||r.sourceEntityId)}</td><td>{String(m.spend??"Not reported")}</td><td>{String(m.impressions??"Not reported")}</td><td>{String(m.reach??"Not reported")}</td><td>{String(m.clicks??"Not reported")}</td><td>{String(m.ctr??"Not reported")}</td><td>{String(m.attributedPurchases??"Not reported")}</td><td>{String(m.reportedRoas??"Not reported")}</td></tr>})}</tbody></table></div></>}</section>
}
