export type Json = string | number | boolean | null | { [key:string]:Json|undefined } | Json[];
type EmptyRelationships = [];
export type Database = { public:{
  Tables:{
    organisations:{ Row:{id:string;name:string;slug:string;created_by:string;logo_url:string|null;website:string|null;industry:string|null;timezone:string;default_currency:string;created_at:string;updated_at:string}; Insert:{id?:string;name:string;slug:string;created_by:string;logo_url?:string|null;website?:string|null;industry?:string|null;timezone?:string;default_currency?:string;created_at?:string;updated_at?:string}; Update:{name?:string;slug?:string;logo_url?:string|null;website?:string|null;industry?:string|null;timezone?:string;default_currency?:string;updated_at?:string}; Relationships:EmptyRelationships };
    profiles:{ Row:{id:string;full_name:string|null;avatar_url:string|null;active_organisation_id:string|null;created_at:string;updated_at:string}; Insert:{id:string;full_name?:string|null;avatar_url?:string|null;active_organisation_id?:string|null}; Update:{full_name?:string|null;avatar_url?:string|null;active_organisation_id?:string|null}; Relationships:EmptyRelationships };
    organisation_members:{ Row:{id:string;organisation_id:string;user_id:string;role:"owner"|"admin"|"manager"|"member"|"viewer";status:"active"|"suspended";created_at:string}; Insert:{id?:string;organisation_id:string;user_id:string;role:"owner"|"admin"|"manager"|"member"|"viewer";status?:"active"|"suspended";created_at?:string}; Update:{role?:"owner"|"admin"|"manager"|"member"|"viewer";status?:"active"|"suspended"}; Relationships:[{foreignKeyName:"organisation_members_organisation_id_fkey";columns:["organisation_id"];isOneToOne:false;referencedRelation:"organisations";referencedColumns:["id"]}] };
    organisation_invitations:{Row:{id:string;organisation_id:string;email:string;role:"admin"|"manager"|"member"|"viewer";token_hash:string;status:"pending"|"accepted"|"cancelled"|"expired";invited_by:string;expires_at:string;accepted_at:string|null;created_at:string;updated_at:string};Insert:{id?:string;organisation_id:string;email:string;role:"admin"|"manager"|"member"|"viewer";token_hash:string;status?:"pending"|"accepted"|"cancelled"|"expired";invited_by:string;expires_at:string;accepted_at?:string|null;created_at?:string;updated_at?:string};Update:{role?:"admin"|"manager"|"member"|"viewer";token_hash?:string;status?:"pending"|"accepted"|"cancelled"|"expired";expires_at?:string;accepted_at?:string|null;updated_at?:string};Relationships:EmptyRelationships};
    integrations:{ Row:{id:string;organisation_id:string;provider:string;provider_account_id:string|null;provider_account_name:string|null;status:string;access_token_encrypted:string|null;refresh_token_encrypted:string|null;token_expires_at:string|null;settings:Json;last_sync_at:string|null;last_sync_status:string|null;last_sync_error:string|null;sync_locked_until:string|null;last_sync_attempt_at:string|null;created_at:string;updated_at:string}; Insert:{id?:string;organisation_id:string;provider:string;provider_account_id?:string|null;provider_account_name?:string|null;status:string;access_token_encrypted?:string|null;refresh_token_encrypted?:string|null;token_expires_at?:string|null;settings?:Json;last_sync_at?:string|null;last_sync_status?:string|null;last_sync_error?:string|null;sync_locked_until?:string|null;last_sync_attempt_at?:string|null}; Update:{status?:string;provider_account_id?:string|null;provider_account_name?:string|null;access_token_encrypted?:string|null;refresh_token_encrypted?:string|null;token_expires_at?:string|null;settings?:Json;last_sync_at?:string|null;last_sync_status?:string|null;last_sync_error?:string|null;sync_locked_until?:string|null;last_sync_attempt_at?:string|null}; Relationships:EmptyRelationships };
    events:{ Row:{id:string;organisation_id:string;integration_id:string|null;source:string;category:string;event_type:string;title:string;description:string|null;severity:string;occurred_at:string;external_id:string|null;raw_payload:Json;metadata:Json;processed_at:string|null;created_at:string}; Insert:{id?:string;organisation_id:string;integration_id?:string|null;source:string;category:string;event_type:string;title:string;description?:string|null;severity:string;occurred_at:string;external_id?:string|null;raw_payload?:Json;metadata?:Json}; Update:Record<string,never>; Relationships:EmptyRelationships };
    integration_logs:{Row:{id:string;organisation_id:string;integration_id:string;provider:string;status:string;started_at:string;finished_at:string|null;duration_ms:number|null;records_received:number;events_imported:number;events_skipped:number;error_count:number;rate_limited:boolean;error_message:string|null;metadata:Json;created_at:string};Insert:{id?:string;organisation_id:string;integration_id:string;provider:string;status:string;started_at?:string;finished_at?:string|null;duration_ms?:number|null;records_received?:number;events_imported?:number;events_skipped?:number;error_count?:number;rate_limited?:boolean;error_message?:string|null;metadata?:Json;created_at?:string};Update:{status?:string;finished_at?:string|null;duration_ms?:number|null;records_received?:number;events_imported?:number;events_skipped?:number;error_count?:number;rate_limited?:boolean;error_message?:string|null;metadata?:Json};Relationships:EmptyRelationships};
    stripe_event_receipts:{Row:{id:string;organisation_id:string;integration_id:string;stripe_account_id:string;livemode:boolean;stripe_event_id:string;stripe_event_type:string;provider_created_at:string;received_at:string;processing_status:string;attempts:number;error_category:string|null;processed_at:string|null};Insert:{id?:string;organisation_id:string;integration_id:string;stripe_account_id:string;livemode:boolean;stripe_event_id:string;stripe_event_type:string;provider_created_at:string;received_at?:string;processing_status?:string;attempts?:number;error_category?:string|null;processed_at?:string|null};Update:{processing_status?:string;attempts?:number;error_category?:string|null;processed_at?:string|null};Relationships:EmptyRelationships};
    insights:{Row:{id:string;organisation_id:string;title:string;summary:string;severity:"info"|"good"|"warning"|"critical";confidence:number;status:"active"|"acknowledged"|"dismissed"|"resolved";rule_id:string;explanation:string;recommendation:string;metadata:Json;source_event_ids:string[];fingerprint:string;acknowledged_at:string|null;dismissed_at:string|null;resolved_at:string|null;created_at:string;updated_at:string};Insert:{id?:string;organisation_id:string;title:string;summary:string;severity:"info"|"good"|"warning"|"critical";confidence:number;status?:"active"|"acknowledged"|"dismissed"|"resolved";rule_id:string;explanation:string;recommendation:string;metadata?:Json;source_event_ids?:string[];fingerprint:string;acknowledged_at?:string|null;dismissed_at?:string|null;resolved_at?:string|null;created_at?:string;updated_at?:string};Update:{title?:string;summary?:string;severity?:"info"|"good"|"warning"|"critical";confidence?:number;status?:"active"|"acknowledged"|"dismissed"|"resolved";rule_id?:string;explanation?:string;recommendation?:string;metadata?:Json;source_event_ids?:string[];acknowledged_at?:string|null;dismissed_at?:string|null;resolved_at?:string|null;updated_at?:string};Relationships:EmptyRelationships};
  };
  Views:Record<string,never>;
  Functions:{create_organisation_with_owner:{Args:{organisation_name:string;organisation_slug:string};Returns:string};accept_organisation_invitation:{Args:{invitation_token_hash:string};Returns:string};is_email_organisation_member:{Args:{target_organisation_id:string;target_email:string};Returns:boolean};acquire_integration_sync_lock:{Args:{target_integration_id:string;target_organisation_id:string};Returns:boolean};release_integration_sync_lock:{Args:{target_integration_id:string;target_organisation_id:string};Returns:undefined}};
  Enums:Record<string,never>; CompositeTypes:Record<string,never>;
} };
