import type{CaseStatus,TaskStatus,UnifiedWork,WorkPriority}from"./types";
const taskTransitions:Record<TaskStatus,readonly TaskStatus[]>={backlog:["open"],open:["in_progress","blocked","waiting","cancelled"],in_progress:["blocked","waiting","completed","cancelled"],blocked:["open","in_progress","cancelled"],waiting:["open","in_progress","cancelled"],completed:["open"],cancelled:["open"]};
const caseTransitions:Record<CaseStatus,readonly CaseStatus[]>={open:["investigating","waiting","resolved","cancelled"],investigating:["waiting","resolved","cancelled"],waiting:["investigating","resolved","cancelled"],resolved:["closed","investigating"],closed:["investigating"],cancelled:["open"]};
export const canTransitionTask=(from:TaskStatus,to:TaskStatus)=>taskTransitions[from].includes(to);
export const canTransitionCase=(from:CaseStatus,to:CaseStatus)=>caseTransitions[from].includes(to);
export function requireTransition(kind:"task"|"case",from:string,to:string,reason?:string){const valid=kind==="task"?canTransitionTask(from as TaskStatus,to as TaskStatus):canTransitionCase(from as CaseStatus,to as CaseStatus);if(!valid)throw new Error(`Invalid ${kind} transition from ${from} to ${to}.`);if((from==="completed"||from==="closed"||from==="cancelled")&&!reason?.trim())throw new Error("A reason is required to reopen work.");}
export function completionBlockers(requiredIncomplete:number,blockingOpen:number,pendingApprovals=0){return[requiredIncomplete?`${requiredIncomplete} required checklist item(s) remain.`:"",blockingOpen?`${blockingOpen} blocking dependency task(s) remain.`:"",pendingApprovals?`${pendingApprovals} linked approval(s) remain pending.`:""].filter(Boolean)}
export function caseClosureBlockers(openTasks:number,pendingApprovals:number,criticalNotifications:number){return[openTasks?`${openTasks} open task(s) remain.`:"",pendingApprovals?`${pendingApprovals} pending approval(s) remain.`:"",criticalNotifications?`${criticalNotifications} unresolved critical notification(s) remain.`:""].filter(Boolean)}
const rank:Record<WorkPriority,number>={low:0,normal:1,high:2,critical:3};
export function sortUnifiedWork(items:UnifiedWork[],now=new Date(),dueSoonHours=24){const soon=now.getTime()+dueSoonHours*3600000,bucket=(x:UnifiedWork)=>{const due=x.dueAt?new Date(x.dueAt).getTime():Infinity,high=rank[x.priority];return due<now.getTime()?(x.priority==="critical"?0:x.priority==="high"?1:2):due<=soon?(x.priority==="critical"?3:x.priority==="high"?4:5):6};return[...items].sort((a,b)=>bucket(a)-bucket(b)||((a.dueAt?new Date(a.dueAt).getTime():Infinity)-(b.dueAt?new Date(b.dueAt).getTime():Infinity))||rank[b.priority]-rank[a.priority]||a.createdAt.localeCompare(b.createdAt)||a.id.localeCompare(b.id))}
