import type {NormalisedEventInput} from "@/types/events";
import type {TranslationContext} from "../connector";
import {GA4_THRESHOLDS as T} from "./config";
import {periodOccurrence} from "./dates";
import {aggregateDimensions,compareMetric} from "./metrics";
import type {GA4Snapshot} from "./schemas";
const rounded=(value:number)=>Math.round(value*100)/100;
const dimensionId=(value:string)=>encodeURIComponent(value.toLowerCase()).slice(0,60);
export function ga4ExternalId(snapshot:GA4Snapshot,eventType:string,metric:string,dimension="total"){return`ga4:${snapshot.propertyId}:${eventType}:${metric}:${snapshot.dates.currentStart}:${snapshot.dates.currentEnd}:${dimensionId(dimension)}`}
export function translateGA4Snapshot(snapshot:GA4Snapshot,context:TranslationContext):NormalisedEventInput[]{
  const events:NormalisedEventInput[]=[];const occurredAt=periodOccurrence(snapshot.dates.currentEnd,snapshot.timeZone);
  const add=(eventType:string,title:string,description:string,severity:NormalisedEventInput["severity"],metric:string,currentValue:number,previousValue:number,dimension?:string,extraMetadata:Record<string,unknown>={})=>{
    const absoluteChange=currentValue-previousValue,percentageChange=previousValue===0?null:absoluteChange/previousValue*100;
    events.push({organisationId:context.organisationId,integrationId:context.integrationId,source:"google_analytics",category:"marketing",eventType,title,description,severity,occurredAt,externalId:ga4ExternalId(snapshot,eventType,metric,dimension),metadata:{propertyId:snapshot.propertyId,metric,currentValue:rounded(currentValue),previousValue:rounded(previousValue),absoluteChange:rounded(absoluteChange),percentageChange:percentageChange===null?null:rounded(percentageChange),currentPeriodStart:snapshot.dates.currentStart,currentPeriodEnd:snapshot.dates.currentEnd,previousPeriodStart:snapshot.dates.previousStart,previousPeriodEnd:snapshot.dates.previousEnd,comparisonType:snapshot.dates.comparisonType,timeZone:snapshot.timeZone,dimension:dimension??null,thresholds:T,...extraMetadata},rawPayload:{currentValue:rounded(currentValue),previousValue:rounded(previousValue)}});
  };
  const traffic=compareMetric("sessions",snapshot.current,snapshot.previous);
  if(snapshot.previous.sessions>=T.minimumSessions&&Math.abs(traffic.absoluteChange)>=T.minimumSessionDifference&&traffic.percentageChange!==null&&Math.abs(traffic.percentageChange)>=T.minimumPercentageChange){
    const up=traffic.absoluteChange>0;add(up?"analytics.traffic_increased":"analytics.traffic_decreased",`Website traffic ${up?"increased":"fell"} ${Math.abs(Math.round(traffic.percentageChange))}% last week`,`Sessions ${up?"increased":"decreased"} from ${snapshot.previous.sessions.toLocaleString()} to ${snapshot.current.sessions.toLocaleString()} compared with the previous seven-day period.`,up?"good":Math.abs(traffic.percentageChange)>=T.severeDeclinePercentage&&snapshot.previous.sessions>=200?"critical":"warning","sessions",snapshot.current.sessions,snapshot.previous.sessions,undefined,{currentKeyEvents:rounded(snapshot.current.keyEvents),previousKeyEvents:rounded(snapshot.previous.keyEvents)});
  }
  if(snapshot.current.sessions===0&&snapshot.previous.sessions>=T.minimumSessions)add("analytics.tracking_inactive","Analytics tracking appears inactive",`No sessions were recorded for the latest complete seven-day period, after ${snapshot.previous.sessions.toLocaleString()} in the previous period.`,"critical","sessions",0,snapshot.previous.sessions);
  const conversions=compareMetric("keyEvents",snapshot.current,snapshot.previous);
  if(snapshot.previous.keyEvents>=T.minimumConversions&&Math.abs(conversions.absoluteChange)>=T.minimumConversionDifference&&conversions.percentageChange!==null&&Math.abs(conversions.percentageChange)>=T.minimumPercentageChange){const up=conversions.absoluteChange>0;add(up?"analytics.conversions_increased":"analytics.conversions_decreased",`Conversions ${up?"increased":"decreased"} ${Math.abs(Math.round(conversions.percentageChange))}%`,`Key events changed from ${snapshot.previous.keyEvents} to ${snapshot.current.keyEvents} in the latest complete week.`,up?"good":snapshot.current.keyEvents===0&&snapshot.previous.keyEvents>=20?"critical":"warning","keyEvents",snapshot.current.keyEvents,snapshot.previous.keyEvents)}
  const engagementPoints=(snapshot.current.engagementRate-snapshot.previous.engagementRate)*100;if(snapshot.previous.sessions>=T.minimumSessions&&Math.abs(engagementPoints)>=T.minimumEngagementRateDifference)add("analytics.engagement_rate_changed",`Engagement rate ${engagementPoints>0?"improved":"declined"}`,`Engagement rate changed by ${Math.abs(rounded(engagementPoints))} percentage points compared with the previous week.`,engagementPoints>0?"good":"warning","engagementRate",snapshot.current.engagementRate,snapshot.previous.engagementRate);
  const currentChannels=aggregateDimensions(snapshot.currentDimensions,"channel"),previousChannels=aggregateDimensions(snapshot.previousDimensions,"channel");
  for(const [channel,eventType] of [["Organic Search","analytics.organic_traffic_changed"],["Paid Search","analytics.paid_traffic_changed"]] as const){const current=currentChannels.get(channel)?.sessions??0,previous=previousChannels.get(channel)?.sessions??0;const change=previous?((current-previous)/previous)*100:null;if(previous>=T.minimumDimensionSessions&&change!==null&&Math.abs(change)>=T.minimumPercentageChange)add(eventType,`${channel} traffic ${change>0?"increased":"decreased"}`,`${channel} sessions changed from ${previous} to ${current} in the latest complete week.`,change>0?"good":"warning","sessions",current,previous,channel)}
  const currentSources=aggregateDimensions(snapshot.currentDimensions,"sourceMedium"),previousSources=aggregateDimensions(snapshot.previousDimensions,"sourceMedium");
  for(const [source,current] of currentSources){const previous=previousSources.get(source)?.sessions??0;if(previous===0&&current.sessions>=T.minimumDimensionSessions)add("analytics.new_source_detected",`New traffic source detected: ${source}`,`${source} generated ${current.sessions} sessions in the latest complete week and none in the preceding week.`,"info","sessions",current.sessions,0,source);else if(/referral/i.test(source)&&previous>=T.minimumDimensionSessions&&current.sessions>=previous*2)add("analytics.referral_spike",`Referral traffic spiked from ${source}`,`${source} referral sessions increased from ${previous} to ${current.sessions}.`,"good","sessions",current.sessions,previous,source)}
  const currentPages=aggregateDimensions(snapshot.currentDimensions,"landingPage"),previousPages=aggregateDimensions(snapshot.previousDimensions,"landingPage");
  for(const [page,current] of currentPages){const previous=previousPages.get(page)?.sessions??0;if(previous>=T.minimumLandingPageSessions){const change=(current.sessions-previous)/previous*100;if(Math.abs(change)>=T.landingPagePercentageChange)add(change>0?"analytics.landing_page_surged":"analytics.landing_page_declined",`Landing page traffic ${change>0?"surged":"declined"}: ${page}`,`Sessions for ${page} changed from ${previous} to ${current.sessions}.`,change>0?"good":"warning","sessions",current.sessions,previous,page)}}
  return events;
}
