import{makeRule,type RuleSpec}from"./factory";
const money={kind:"money",keys:["amount","currency"],points:40,label:"amount and currency"}as const,id=(...keys:string[])=>({kind:"id"as const,keys,points:100,label:keys[0]}),url=(...keys:string[])=>({kind:"url"as const,keys,points:80,label:"source URL"}),utm={kind:"attribution"as const,keys:["campaign_id","utm_campaign","campaign"],points:90,label:"campaign identifier"},email={kind:"email"as const,keys:["email","customer_email","sender","attendee"],points:35,label:"non-public email domain"};
const specs:RuleSpec[]=[
 {key:"shopify-stripe-payment",version:1,name:"Shopify order and Stripe payment",description:"Links transactional records using explicit references and matching monetary evidence.",providers:["shopify","stripe"],sourceEventTypes:["shopify.order_created","shopify.order_paid","shopify.order_refunded"],targetEventTypes:["stripe.payment_succeeded","stripe.checkout_completed","stripe.payment_refunded"],relationshipType:"payment_fulfilment",direction:"downstream",timeWindowSeconds:86400,minimumScore:70,signals:[id("order_id","order_number","checkout_id","payment_id","providerObjectId"),money,email]},
 {key:"meta-analytics-campaign",version:1,name:"Meta Ads and Analytics activity",description:"Correlates matching campaign attribution; it does not claim causation.",providers:["meta_ads","google_analytics"],sourceEventTypes:[],targetEventTypes:[],relationshipType:"marketing_response",direction:"downstream",timeWindowSeconds:86400,minimumScore:70,signals:[utm,url("landing_page","page","source_url")]},
 {key:"linkedin-analytics-campaign",version:1,name:"LinkedIn and Analytics activity",description:"Correlates matching campaign attribution; it does not claim causation.",providers:["linkedin","google_analytics"],sourceEventTypes:[],targetEventTypes:[],relationshipType:"marketing_response",direction:"downstream",timeWindowSeconds:86400,minimumScore:70,signals:[utm,url("landing_page","page","source_url")]},
 {key:"search-console-organic",version:1,name:"Search Console and Analytics organic activity",description:"Links matching landing pages in the same organic activity window.",providers:["google_search_console","google_analytics"],sourceEventTypes:[],targetEventTypes:[],relationshipType:"marketing_response",direction:"bidirectional",timeWindowSeconds:86400,minimumScore:70,signals:[url("page","landing_page","source_url"),{kind:"text",keys:["source_medium","medium"],points:20,label:"organic source"}]},
 {key:"gmail-calendar-follow-up",version:1,name:"Gmail enquiry and Calendar meeting",description:"Links an enquiry with a subsequent meeting using explicit participant or reference evidence.",providers:["gmail","google_calendar"],sourceEventTypes:[],targetEventTypes:[],relationshipType:"operational_follow_up",direction:"downstream",timeWindowSeconds:604800,minimumScore:35,signals:[id("thread_id","message_id","calendar_event_id"),email,{kind:"text",keys:["customer_reference","project_code"],points:35,label:"customer or project reference"}]},
 {key:"gmail-shopify-order",version:1,name:"Gmail enquiry and Shopify order",description:"Links enquiry and order evidence using customer or order references.",providers:["gmail","shopify"],sourceEventTypes:[],targetEventTypes:[],relationshipType:"conversion_path",direction:"downstream",timeWindowSeconds:2592000,minimumScore:35,signals:[id("order_id","order_number","customer_reference"),email]},
 {key:"notion-github-project",version:1,name:"Notion task and GitHub delivery",description:"Links explicit repository, pull request, commit, branch, or project references.",providers:["notion","github"],sourceEventTypes:[],targetEventTypes:[],relationshipType:"same_project",direction:"bidirectional",timeWindowSeconds:2592000,minimumScore:70,signals:[id("commit_sha","pull_request_number","issue_number","project_code","ticket_reference"),url("github_url","repository_url","source_url")]},
 {key:"slack-notion-reference",version:1,name:"Slack and Notion reference",description:"Links a Slack message only when it carries an exact Notion page reference.",providers:["slack","notion"],sourceEventTypes:[],targetEventTypes:[],relationshipType:"same_project",direction:"undirected",timeWindowSeconds:2592000,minimumScore:70,signals:[id("notion_page_id","project_code"),url("notion_url","source_url")]},
 {key:"slack-github-reference",version:1,name:"Slack and GitHub reference",description:"Links exact GitHub URLs, commit SHAs, or repository-qualified references.",providers:["slack","github"],sourceEventTypes:[],targetEventTypes:[],relationshipType:"same_project",direction:"undirected",timeWindowSeconds:2592000,minimumScore:70,signals:[id("commit_sha","pull_request_number","issue_number","project_code"),url("github_url","repository_url","source_url")]},
 {key:"github-analytics-window",version:1,name:"Deployment and Analytics window",description:"Records a bounded temporal sequence without claiming the deployment caused the change.",providers:["github","google_analytics"],sourceEventTypes:["deployment.created","deployment.success","workflow.success"],targetEventTypes:[],relationshipType:"temporal_sequence",direction:"downstream",timeWindowSeconds:86400,minimumScore:10,signals:[],temporalOnly:true},
 {key:"manual-transaction-reference",version:1,name:"Manual record and transaction",description:"Links allowlisted manual identifiers to transaction evidence.",providers:["manual","stripe"],sourceEventTypes:[],targetEventTypes:[],relationshipType:"same_transaction",direction:"undirected",timeWindowSeconds:2592000,minimumScore:60,signals:[id("invoice_number","order_number","transaction_id","external_reference","customer_reference"),money]},
];export const correlationRules=specs.map(makeRule);
