import{NextResponse}from"next/server";import{cookies}from"next/headers";import{createClient}from"@/lib/supabase/server";import{hasPermission,type OrganisationRole}from"@/lib/auth/permissions";import{exchangeCode,stateMatches}from"@/lib/integrations/meta-ads/oauth";import{MetaAdsClient}from"@/lib/integrations/meta-ads/client";import{metaEnv}from"@/lib/integrations/meta-ads/config";import{encryptToken}from"@/lib/security/token-crypto";import type{Json}from"@/types/database";
const back=(url:URL,kind:"error"|"success",message:string,path="/app/integrations")=>NextResponse.redirect(new URL(`${path}?${kind}=${encodeURIComponent(message)}`,url));
export async function GET(request:Request){
  const url=new URL(request.url),store=await cookies(),raw=store.get("ghost_meta_oauth")?.value;store.delete("ghost_meta_oauth");
  if(url.searchParams.get("error"))return back(url,"error","Meta Ads authorization was denied.");
  let state:{state:string;userId:string;organisationId:string;provider:string;returnTo:string;createdAt:number}|undefined;try{state=raw?JSON.parse(raw):undefined}catch{}
  const code=url.searchParams.get("code");if(!state||state.provider!=="meta_ads"||Date.now()-state.createdAt>600_000||!stateMatches(state.state,url.searchParams.get("state"))||!code)return back(url,"error","Meta Ads authorization expired or failed validation.");
  try{
    const supabase=await createClient(),{data:{user}}=await supabase.auth.getUser();if(!user||user.id!==state.userId)throw new Error("Your Ghost session changed. Restart Meta authorization.");
    const{data:member}=await supabase.from("organisation_members").select("role").eq("organisation_id",state.organisationId).eq("user_id",user.id).eq("status","active").maybeSingle();if(!member||!hasPermission(member.role as OrganisationRole,"integration.manage"))throw new Error("You no longer have permission to connect Meta Ads here.");
    const token=await exchangeCode(code),client=new MetaAdsClient(token.access_token!),[identity,permissions,accounts]=await Promise.all([client.identity(),client.permissions(),client.accounts()]),granted=permissions.filter(p=>p.status==="granted").map(p=>p.permission),declined=permissions.filter(p=>p.status!=="granted").map(p=>p.permission),expiresAt=token.expires_in?new Date(Date.now()+token.expires_in*1000).toISOString():null;
    const{data:existing}=await supabase.from("integrations").select("id,settings").eq("organisation_id",state.organisationId).eq("provider","meta_ads").eq("provider_account_id",identity.id).maybeSingle(),old=existing?.settings&&typeof existing.settings==="object"&&!Array.isArray(existing.settings)?existing.settings as Record<string,Json>:{},previous=Array.isArray(old.accounts)?old.accounts as{accountId?:string;selected?:boolean}[]:[],eligible=accounts.filter(a=>a.accessState==="available");
    const values={provider_account_id:identity.id,provider_account_name:identity.name,status:"connected",access_token_encrypted:encryptToken(token.access_token!),refresh_token_encrypted:null,token_expires_at:expiresAt,settings:{...old,metaUserId:identity.id,metaUserName:identity.name,accounts:accounts.map(a=>({...a,selected:previous.find(p=>p.accountId===a.accountId)?.selected??(eligible.length===1&&a.accountId===eligible[0]?.accountId)})),grantedPermissions:granted,declinedPermissions:declined,tokenIssuedAt:new Date().toISOString(),graphApiVersion:metaEnv().version,configurationStatus:eligible.length===1?"ready":"property_required",initialSyncComplete:Boolean(old.initialSyncComplete)}as Json,last_sync_status:"connected",last_sync_error:null};
    const result=existing?await supabase.from("integrations").update(values).eq("id",existing.id).eq("organisation_id",state.organisationId):await supabase.from("integrations").insert({organisation_id:state.organisationId,provider:"meta_ads",...values});if(result.error)throw new Error("Meta authorized Ghost, but the integration could not be saved.");
    if(existing?.id)await supabase.from("integration_logs").insert({organisation_id:state.organisationId,integration_id:existing.id,provider:"meta_ads",status:"finished",records_received:accounts.length,events_imported:0,events_skipped:0,error_count:0,metadata:{operation:"oauth_connected",graphApiVersion:metaEnv().version}});
    return back(url,"success",`Meta Ads connected as ${identity.name}.`,state.returnTo);
  }catch(error){return back(url,"error",error instanceof Error?error.message:"Meta Ads connection failed.")}
}
