import "server-only";
import {GmailError} from "./errors";import type {ConnectorCredentialUpdate} from "../connector";import type {GmailMessage,GmailProfile,GmailSettings} from "./types";
type Credentials={accessToken:string;refreshToken?:string;expiresAt?:string};
const base="https://gmail.googleapis.com/gmail/v1/users/me";
export class GmailClient{private access:string;private expiry?:string;private updated?:ConnectorCredentialUpdate;constructor(private credentials:Credentials,private request:typeof fetch=fetch){this.access=credentials.accessToken;this.expiry=credentials.expiresAt}credentialUpdate(){return this.updated}
private async token(){if(!this.expiry||new Date(this.expiry).getTime()>Date.now()+60000)return this.access;if(!this.credentials.refreshToken)throw new GmailError("unauthorized","Gmail authorization expired. Reconnect the mailbox.");const response=await this.request("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID??"",client_secret:process.env.GOOGLE_CLIENT_SECRET??"",grant_type:"refresh_token",refresh_token:this.credentials.refreshToken})});const body=await response.json() as {access_token?:string;expires_in?:number};if(!response.ok||!body.access_token)throw new GmailError("unauthorized","Gmail authorization could not be refreshed. Reconnect the mailbox.");this.access=body.access_token;this.expiry=new Date(Date.now()+(body.expires_in??3600)*1000).toISOString();this.updated={accessToken:this.access,refreshToken:this.credentials.refreshToken,expiresAt:this.expiry};return this.access}
private async get<T>(url:string){let response:Response;try{response=await this.request(url,{headers:{Authorization:`Bearer ${await this.token()}`},signal:AbortSignal.timeout(15000)})}catch{throw new GmailError("network","Gmail could not be reached.")}if(!response.ok){const kind=response.status===401?"unauthorized":response.status===403?"scope":response.status===429?"rate_limit":"provider";throw new GmailError(kind,kind==="scope"?"Gmail read-only permission is missing. Reconnect and approve access.":kind==="rate_limit"?"Gmail rate limit reached. Try again later.":"Gmail API request failed.")}return response.json() as Promise<T>}
profile(){return this.get<GmailProfile>(`${base}/profile`)}
message(id:string){return this.get<GmailMessage>(`${base}/messages/${encodeURIComponent(id)}?format=metadata&metadataHeaders=From&metadataHeaders=To&metadataHeaders=Cc&metadataHeaders=Subject`)}
async collect(settings:GmailSettings){const ids=new Set<string>(),initial=!settings.initialSyncComplete,pagesLimit=5,max=initial?250:500;let pageToken:string|undefined,pages=0,historyId=settings.historyId,fallback=false;try{if(!initial&&historyId){do{const url=new URL(`${base}/history`);url.searchParams.set("startHistoryId",historyId);url.searchParams.set("historyTypes","messageAdded");url.searchParams.set("maxResults","100");if(pageToken)url.searchParams.set("pageToken",pageToken);const data=await this.get<{history?:{messagesAdded?:{message:{id:string}}[]}[];nextPageToken?:string;historyId?:string}>(url.toString());data.history?.forEach(item=>item.messagesAdded?.forEach(entry=>ids.add(entry.message.id)));pageToken=data.nextPageToken;historyId=data.historyId??historyId;pages++}while(pageToken&&pages<pagesLimit&&ids.size<max)}else fallback=true}catch(error){if(error instanceof GmailError&&error.kind==="provider")fallback=true;else throw error}if(fallback){pageToken=undefined;do{const url=new URL(`${base}/messages`);url.searchParams.set("q",`newer_than:${settings.initialWindowDays??7}d -in:spam -in:trash`);url.searchParams.set("maxResults","100");if(pageToken)url.searchParams.set("pageToken",pageToken);const data=await this.get<{messages?:{id:string}[];nextPageToken?:string}>(url.toString());data.messages?.forEach(item=>ids.add(item.id));pageToken=data.nextPageToken;pages++}while(pageToken&&pages<pagesLimit&&ids.size<max)}const messages:GmailMessage[]=[];let failed=0;for(const id of [...ids].slice(0,max)){try{messages.push(await this.message(id))}catch{failed++}}const profile=await this.profile();return{messages,historyId:profile.historyId,pages,failed,initial,fallback}}
async revoke(){try{await this.request(`https://oauth2.googleapis.com/revoke?token=${encodeURIComponent(await this.token())}`,{method:"POST"})}catch{}}
}
