export const INTELLIGENCE_CONFIG = {
  rollingWindowDays: 30,
  deploymentCorrelationHours: 24,
  failedDeploymentCorrelationHours: 48,
  workflowFailureWindowHours: 72,
  workflowFailureCount: 3,
  stableConversionTolerancePercent: 10,
  recoveryWindowDays: 14,
  maxEvents: 5000,
  // Week-on-week commerce, payments and advertising rules.
  comparisonWindowDays: 7,
  orderDeclinePercent: 30,
  orderDeclineCriticalPercent: 60,
  minimumPreviousOrders: 10,
  refundWindowDays: 14,
  refundRatePercent: 10,
  minimumRefunds: 3,
  paymentFailureRatePercent: 15,
  paymentFailureCriticalPercent: 30,
  minimumPaymentFailures: 5,
  revenueDeclinePercent: 30,
  minimumPreviousPayments: 10,
  adReturnDeclinePercent: 30,
  adSpendSteadyTolerancePercent: 10,
  minimumPreviousAdPurchases: 5,
  adSpendIncreasePercent: 20,
  crossOrderDeclinePercent: 20,
  moneyAtRiskWindowDays: 30,
} as const;
