import"server-only";import type{ShopifyCollection,ShopifyOrder,ShopifyProduct,ShopifyRecord}from"./types";import{SHOPIFY_API_VERSION,SHOPIFY_LIMITS,shopifyEnv}from"./config";import type{ConnectorCredentialUpdate}from"../connector";
export class ShopifyError extends Error{constructor(public kind:"unauthorized"|"forbidden"|"rate_limit"|"provider"|"timeout",message:string){super(message)}}
type DiscountNode={id:string;discount:{title?:string;status?:string;startsAt?:string;endsAt?:string}};
export class ShopifyClient{
  private access:string;private expiry?:string;private update?:ConnectorCredentialUpdate;private requests=0;
  constructor(private credentials:{shop:string;accessToken:string;refreshToken?:string;expiresAt?:string},private request:typeof fetch=fetch){this.access=credentials.accessToken;this.expiry=credentials.expiresAt}
  credentialUpdate(){return this.update}
  private async token(){if(!this.expiry||Date.parse(this.expiry)>Date.now()+60_000)return this.access;if(!this.credentials.refreshToken)throw new ShopifyError("unauthorized","Shopify access expired. Reconnect the store.");const env=shopifyEnv(),response=await this.request(`https://${this.credentials.shop}/admin/oauth/access_token`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({client_id:env.clientId,client_secret:env.clientSecret,grant_type:"refresh_token",refresh_token:this.credentials.refreshToken}),signal:AbortSignal.timeout(15_000)}),body=await response.json()as{access_token?:string;refresh_token?:string;expires_in?:number};if(!response.ok||!body.access_token)throw new ShopifyError("unauthorized","Shopify access could not be refreshed.");this.access=body.access_token;this.expiry=new Date(Date.now()+(body.expires_in??3600)*1000).toISOString();this.update={accessToken:this.access,refreshToken:body.refresh_token??this.credentials.refreshToken,expiresAt:this.expiry};return this.access}
  private async graph<T>(query:string,variables:Record<string,unknown>={}){if(++this.requests>SHOPIFY_LIMITS.requests)throw new ShopifyError("rate_limit","Shopify request safety limit reached.");let response:Response;try{response=await this.request(`https://${this.credentials.shop}/admin/api/${SHOPIFY_API_VERSION}/graphql.json`,{method:"POST",headers:{"content-type":"application/json","X-Shopify-Access-Token":await this.token()},body:JSON.stringify({query,variables}),signal:AbortSignal.timeout(15_000)})}catch{throw new ShopifyError("timeout","Shopify did not respond before timeout.");}const body=await response.json()as{data?:T;errors?:{message:string}[]};if(!response.ok||body.errors?.length)throw new ShopifyError(response.status===401?"unauthorized":response.status===403?"forbidden":response.status===429?"rate_limit":"provider","Shopify Admin API request failed.");return body.data!}
  async shop(){return this.graph<{shop:{name:string;myshopifyDomain:string;currencyCode:string;ianaTimezone:string;plan:{displayName:string}}}>(`query{shop{name myshopifyDomain currencyCode ianaTimezone plan{displayName}}}`).then(x=>x.shop)}
  async records(since:string){const data=await this.graph<{orders:{nodes:ShopifyOrder[]};products:{nodes:ShopifyProduct[]};collections:{nodes:ShopifyCollection[]};discountNodes:{nodes:DiscountNode[]}}>(`query Sync($orderQuery:String!){orders(first:100,sortKey:UPDATED_AT,reverse:true,query:$orderQuery){nodes{id name createdAt updatedAt displayFinancialStatus displayFulfillmentStatus cancelledAt currentTotalPriceSet{shopMoney{amount currencyCode}} totalRefundedSet{shopMoney{amount currencyCode}} customer{id numberOfOrders defaultAddress{countryCodeV2}} lineItems(first:20){nodes{title quantity originalTotalSet{shopMoney{amount currencyCode}}}}}}products(first:100,sortKey:UPDATED_AT,reverse:true){nodes{id title handle status createdAt updatedAt totalInventory onlineStoreUrl collections(first:20){nodes{id title}}}}collections(first:100,sortKey:UPDATED_AT,reverse:true){nodes{id title updatedAt productsCount{count}}}discountNodes(first:100,reverse:true){nodes{id discount{__typename ... on DiscountCodeBasic{title status startsAt endsAt} ... on DiscountAutomaticBasic{title status startsAt endsAt}}}}}`,{orderQuery:`updated_at:>=${since}`});return[...data.orders.nodes.map(data=>({kind:"order"as const,data})),...data.products.nodes.map(data=>({kind:"product"as const,data})),...data.collections.nodes.map(data=>({kind:"collection"as const,data})),...data.discountNodes.nodes.map(node=>({kind:"discount"as const,data:{id:node.id,title:node.discount.title??"Discount",status:node.discount.status??"UNKNOWN",startsAt:node.discount.startsAt,endsAt:node.discount.endsAt,updatedAt:new Date().toISOString()}}))]satisfies ShopifyRecord[]}
  async revoke(){return}
}
